<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authorization Models
    |--------------------------------------------------------------------------
    */

    'models' => [

        'permission' => App\Models\Permissions\Permission::class,

        'role' => App\Models\Users\Roles\Role::class
    ],

    'table_names' => [

        'users' => 'users',

        'roles' => 'roles',

        'permissions' => 'permissions',

        'permissionable' => 'permissionable',

        'user_has_roles' => 'user_has_roles',

        'user_has_permissions' => 'user_has_permissions'
    ],

    'permissions' => [

        [
            'name' => 'Manage Super Admin',
            'system_name' => 'user_admin_super',
            'display_name' => 'Add/Edit/Delete user type Super Admin',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Super Admin',
            'roles' => [
                'adsupr',
            ]
        ],
        [
            'name' => 'Manage Brokerage Admin',
            'system_name' => 'user_admin_brokerage',
            'display_name' => 'Add/Edit/Delete user type Brokerage Admin',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Brokerage Admin',
            'roles' => [
                'adsupr',
            ]
        ],
        [
            'name' => 'Manage System Admin',
            'system_name' => 'user_admin_system',
            'display_name' => 'Add/Edit/Delete user type System Admin',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type System Admin',
            'roles' => [
                'adsupr',
                'adbrok',
            ]
        ],
        [
            'name' => 'Manage Managers',
            'system_name' => 'user_manager',
            'display_name' => 'Add/Edit/Delete user type Manager',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Manager',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
            ]
        ],
        [
            'name' => 'Manage Staff',
            'system_name' => 'user_staff',
            'display_name' => 'Add/Edit/Delete user type Staff',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Staff',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ]
        ],
        [
            'name' => 'Manage Account Executive',
            'system_name' => 'user_accountexecutive',
            'display_name' => 'Add/Edit/Delete user type Account Executive',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Account Executive',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stagsv',
            ]
        ],
        [
            'name' => 'Manage Affiliated Agent',
            'system_name' => 'user_agent_affiliated',
            'display_name' => 'Add/Edit/Delete user type Affiliated Agent',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Affiliated Agent',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stagsv',
            ]
        ],
        [
            'name' => 'Manage Unaffiliated Agent',
            'system_name' => 'user_agent_unaffiliated',
            'display_name' => 'Add/Edit/Delete user type Unaffiliated Agent',
            'module_name' => 'users',
            'description' => 'Add/Edit/Delete user type Unaffiliated Agent',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stagsv',
            ]
        ],
        [
            'name' => 'Add user type Contact',
            'system_name' => 'user_contact_add',
            'display_name' => 'Add user type Contact',
            'module_name' => 'users',
            'description' => 'Add user type Contact',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ]
        ],
        [
            'name' => 'Add user type Sales Vendor',
            'system_name' => 'user_vendor_sales_add',
            'display_name' => 'Add user type Sales Vendor',
            'module_name' => 'users',
            'description' => 'Add user type Sales Vendor',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ]
        ],
        [
            'name' => 'Add user type Maintenance Vendor',
            'system_name' => 'user_vendor_maintenance_add',
            'display_name' => 'Add user type Maintenance Vendor',
            'module_name' => 'users',
            'description' => 'Add user type Maintenance Vendor',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgmtnc',
                'stmtnc'

            ]
        ],
        [
            'name' => 'Access to "Contacts" database',
            'system_name' => 'contacts_access',
            'display_name' => 'Access to Contacts module',
            'module_name' => 'contacts',
            'description' => 'Access to Contacts module',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View all contacts within the database',
            'system_name' => 'contacts_all_view',
            'display_name' => 'View all contacts',
            'module_name' => 'contacts',
            'description' => 'View all contacts',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'View user type staff',
            'system_name' => 'contacts_staff_view',
            'display_name' => 'View Staff contact types',
            'module_name' => 'contacts',
            'description' => 'View Staff contact types',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View user type manager',
            'system_name' => 'contacts_manager_view',
            'display_name' => 'View manager contact types',
            'module_name' => 'contacts',
            'description' => 'View manager contact types',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View user type account executive',
            'system_name' => 'contacts_accountexecutive_view',
            'display_name' => 'View Account Executive contact types',
            'module_name' => 'contacts',
            'description' => 'View Account Executive contact types',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View user type affiliated agent',
            'system_name' => 'contacts_agent_affiliated_view',
            'display_name' => 'View Affiliated Agent contact types',
            'module_name' => 'contacts',
            'description' => 'View Affiliated Agent contact types',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Export all contacts',
            'system_name' => 'contacts_all_export',
            'display_name' => 'Export all contact types',
            'module_name' => 'contacts',
            'description' => 'Export all contact types',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'View contact types buyer if created by user',
            'system_name' => 'contacts_buyer_owned_view',
            'display_name' => 'View contact type buyer, if created by the user',
            'module_name' => 'contacts',
            'description' => 'View contact type buyer, if created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View contact types seller if created by user',
            'system_name' => 'contacts_seller_owned_view',
            'display_name' => 'View contact type seller, if created by the user',
            'module_name' => 'contacts',
            'description' => 'View contact type seller, if created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View contact types tenant if created by user',
            'system_name' => 'contacts_tenant_owned_view',
            'display_name' => 'View contact type tenant, if created by the user',
            'module_name' => 'contacts',
            'description' => 'View contact type tenant, if created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View contact type buyer if assigned to, but not created by user',
            'system_name' => 'contacts_buyer_assigned_view',
            'display_name' => 'View contact type buyer, if assigned to but not created by the user',
            'module_name' => 'contacts',
            'description' => 'View contact type buyer, if assigned to but not created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View contact type seller if assigned to, but not created by user',
            'system_name' => 'contacts_seller_assigned_view',
            'display_name' => 'View contact type seller, if assigned to but not created by the user',
            'module_name' => 'contacts',
            'description' => 'View contact type seller, if assigned to but not created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View contact type tenant if assigned to, but not created by user',
            'system_name' => 'contacts_tenant_assigned_view',
            'display_name' => 'View contact type tenant, if assigned to but not created by the user',
            'module_name' => 'contacts',
            'description' => 'View contact type tenant, if assigned to but not created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View vendor within same market',
            'system_name' => 'contacts_vendor_market_view',
            'display_name' => 'View only vendors within the same market',
            'module_name' => 'contacts',
            'description' => 'View only vendors within the same market',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View additional information "Page"',
            'system_name' => 'contacts_additionalinformation_view',
            'display_name' => 'View additional information section of the contact detail',
            'module_name' => 'contacts',
            'description' => 'View additional information section of the contact detail',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'Edit Additional Information ',
            'system_name' => 'contacts_additionalinformation_edit',
            'display_name' => 'Edit Additional Information section of the contact detail',
            'module_name' => 'contacts',
            'description' => 'Edit Additional Information section of the contact detail',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'mgacct',
                'stagsv',
                'stacct',
            ],
        ],
        [
            'name' => 'Delete Additional Information',
            'system_name' => 'contacts_additionalinformation_delete',
            'display_name' => 'Delete information in the Additional Information section of contact detail',
            'module_name' => 'contacts',
            'description' => 'Delete information in the Additional Information section of contact detail',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'mgacct',
                'stagsv',
                'stacct',
            ],
        ],
        [
            'name' => 'Manage Documents',
            'system_name' => 'contacts_documents',
            'display_name' => 'Add/View/Delete documents in the Documents section of contact detail',
            'module_name' => 'contacts',
            'description' => 'Add/View/Delete documents in the Documents section of contact detail',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'Add a Note',
            'system_name' => 'contacts_note_add',
            'display_name' => 'Add a Note',
            'module_name' => 'contacts',
            'description' => 'Add a Note',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Edit own note',
            'system_name' => 'contacts_note_own_edit',
            'display_name' => 'User can only edit a note they created',
            'module_name' => 'contacts',
            'description' => 'User can only edit a note they created',
            'roles' => [
                'stcomp',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',

            ],
        ],
        [
            'name' => 'Edit all notes',
            'system_name' => 'contacts_note_all_edit',
            'display_name' => 'Ability to edit any note',
            'module_name' => 'contacts',
            'description' => 'Ability to edit any note',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'Delete own note',
            'system_name' => 'contacts_note_own_delete',
            'display_name' => 'Ability to delete a note they created',
            'module_name' => 'contacts',
            'description' => 'Ability to delete a note they created',
            'roles' => [
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Delete note created by another user',
            'system_name' => 'contacts_note_all_delete',
            'display_name' => 'Ability to delete any note',
            'module_name' => 'contacts',
            'description' => 'Ability to delete any note',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'View notes marked "Staff Only"',
            'system_name' => 'contacts_notes_staff_view',
            'display_name' => 'View notes marked "Staff only"',
            'module_name' => 'contacts',
            'description' => 'View notes marked "Staff only"',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'View notes marked "All"',
            'system_name' => 'contacts_notes_all_view',
            'display_name' => 'View notes marked "all"',
            'module_name' => 'contacts',
            'description' => 'View notes marked "all"',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Manage a headline',
            'system_name' => 'contacts_headline',
            'display_name' => 'Add/Edit/Delete a headline',
            'module_name' => 'contacts',
            'description' => 'Add/Edit/Delete a headline',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'Impersonate a staff member',
            'system_name' => 'contacts_staff_impersonate',
            'display_name' => 'Ability to impersonate a staff member',
            'module_name' => 'contacts',
            'description' => 'Ability to impersonate a staff member',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
            ],
        ],
        [
            'name' => 'Impersonate an agent user',
            'system_name' => 'contacts_agent_affiliated_impersonate',
            'display_name' => 'Ability to impersonate an affiliated agent',
            'module_name' => 'contacts',
            'description' => 'Ability to impersonate an affiliated agent',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stcomp',
            ],
        ],
        [
            'name' => 'Impersonate an account executive user',
            'system_name' => 'contacts_accountexecutive_impersonate',
            'display_name' => 'Ability to impersonate an account executive',
            'module_name' => 'contacts',
            'description' => 'Ability to impersonate an account executive',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stcomp',
            ],
        ],
        [
            'name' => 'Ability to export only contacts user owns',
            'system_name' => 'contacts_own_export',
            'display_name' => 'User can export only contacts they have created',
            'module_name' => 'contacts',
            'description' => 'User can export only contacts they have created',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Ability to import contacts',
            'system_name' => 'contacts_import',
            'display_name' => 'Ability to import contacts',
            'module_name' => 'contacts',
            'description' => 'Ability to import contacts',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Add contact to marketing campaign',
            'system_name' => 'contacts_campaign_add',
            'display_name' => 'Add a contact to an active marketing campaign',
            'module_name' => 'contacts',
            'description' => 'Add a contact to an active marketing campaign',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Remove a contact from a marketing campaign',
            'system_name' => 'contacts_campaign_delete',
            'display_name' => 'Remove a contact froma marketing campaign',
            'module_name' => 'contacts',
            'description' => 'Remove a contact froma marketing campaign',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgbzdv',
                'stbzdv',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Send a message',
            'system_name' => 'contaacts_message_send',
            'display_name' => 'Send an email from the platform',
            'module_name' => 'contacts',
            'description' => 'Send an email from the platform',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View your own activity log',
            'system_name' => 'contacts_activity_own_view',
            'display_name' => 'User can view their own activity log',
            'module_name' => 'contacts',
            'description' => 'User can view their own activity log',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View activity log of staff',
            'system_name' => 'contacts_activity_staff_view',
            'display_name' => 'User can view activity log of staff contact types',
            'module_name' => 'contacts',
            'description' => 'User can view activity log of staff contact types',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'View activity log of affiliated agents',
            'system_name' => 'contacts_activity_agent_affiliated_view',
            'display_name' => 'User can view activity log of affiliated agent contact types',
            'module_name' => 'contacts',
            'description' => 'User can view activity log of affiliated agent contact types',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'View activity log of Account Executives',
            'system_name' => 'contacts_activity_accountexecutive_view',
            'display_name' => 'User can view activity log of Account Executive contact types',
            'module_name' => 'contacts',
            'description' => 'User can view activity log of Account Executive contact types',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'View activity log of managers',
            'system_name' => 'contacts_activity_managers_view',
            'display_name' => 'User can view activity log of manager contact types',
            'module_name' => 'contacts',
            'description' => 'User can view activity log of manager contact types',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst'
            ],
        ],
        [
            'name' => 'Manage user type Manager',
            'system_name' => 'contacts_manager',
            'display_name' => 'Add/Edit/Delete contact type Manager',
            'module_name' => 'contacts',
            'description' => 'Add/Edit/Delete contact type Manager',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst'
            ],
        ],
        [
            'name' => 'Manage user type Staff',
            'system_name' => 'contacts_staff',
            'display_name' => 'Add/Edit/Delete contact type Staff',
            'module_name' => 'contacts',
            'description' => 'Add/Edit/Delete contact type Staff',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'Manage user type account executive',
            'system_name' => 'contacts_accountexecutive',
            'display_name' => 'Add/Edit/Delete contact type Account Executive',
            'module_name' => 'contacts',
            'description' => 'Add/Edit/Delete contact type Account Executive',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stagsv',
            ],
        ],
        [
            'name' => 'Manage user type Affiliated Agent',
            'system_name' => 'contacts_agent_affiliated',
            'display_name' => 'Add/Edit/Delete contact type Affiliate Agent',
            'module_name' => 'contacts',
            'description' => 'Add/Edit/Delete contact type Affiliate Agent',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stagsv',
            ],
        ],
        [
            'name' => 'Manage user type Unaffiliated Agent',
            'system_name' => 'contacts_agent_unaffiliated',
            'display_name' => 'Add/Edit/Delete contact type Unaffiliated Agent',
            'module_name' => 'contacts',
            'description' => 'Add/Edit/Delete contact type Unaffiliated Agent',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgagsv',
                'stagsv',
            ],
        ],
        [
            'name' => 'Edit fields on a contact created by you',
            'system_name' => 'contacts_owned_edit',
            'display_name' => 'User can edit only contacts they created',
            'module_name' => 'contacts',
            'description' => 'User can edit only contacts they created',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Cannot edit "Assigned to" field on a non-owned contact',
            'system_name' => 'contacts_notowned_assignedto_noedit',
            'display_name' => 'User cannot edit "Assigned to" field on a contact they did not create',
            'module_name' => 'contacts',
            'description' => 'User cannot edit "Assigned to" field on a contact they did not create',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Cannot edit "Lead Status" on a non-owned contact',
            'system_name' => 'contacts_notowned_leadstatus_noedit',
            'display_name' => 'User cannot edit "Lead Status" field on a contact they did not create',
            'module_name' => 'contacts',
            'description' => 'User cannot edit "Lead Status" field on a contact they did not create',
            'roles' => [
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',

            ],
        ],
        [
            'name' => 'Cannot edit "Business Dev. Rep" on a non-owned contact',
            'system_name' => 'contacts_notowned_businessdevrep_noedit',
            'display_name' => 'User cannot edit "Business Dev. Rep" field on a contact they did not create',
            'module_name' => 'contacts',
            'description' => 'User cannot edit "Business Dev. Rep" field on a contact they did not create',
            'roles' => [
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Cannot edit "Source" field on a non-owned contact',
            'system_name' => 'contacts_notowned_source_noedit',
            'display_name' => 'User cannot edit "Source" field on a contact they did not create',
            'module_name' => 'contacts',
            'description' => 'User cannot edit "Source" field on a contact they did not create',
            'roles' => [
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Delete contacts created by you',
            'system_name' => 'contacts_owned_delete',
            'display_name' => 'Delete an owned contact',
            'module_name' => 'contacts',
            'description' => 'Delete an owned contact',
            'roles' => [
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Delete any contact',
            'system_name' => 'contacts_all_delete',
            'display_name' => 'Delete any contact',
            'module_name' => 'contacts',
            'description' => 'Delete any contact',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'Add contact type sales vendor',
            'system_name' => 'contacts_vendor_sales_add',
            'display_name' => 'Add contact type sales vendor',
            'module_name' => 'contacts',
            'description' => 'Add contact type sales vendor',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Add contact type maintenance vendor',
            'system_name' => 'contacts_vendor_maintenance',
            'display_name' => 'Add contact type maintenance vendor',
            'module_name' => 'contacts',
            'description' => 'Add contact type maintenance vendor',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgmtnc',
                'stmtnc',
            ],
        ],
        [
            'name' => 'Edit field "Assigned Date" on contact detail',
            'system_name' => 'contacts_notowned_assigneddate_edit',
            'display_name' => 'User can edit "Assigned Date" field on Contact Detail',
            'module_name' => 'contacts',
            'description' => 'User can edit "Assigned Date" field on Contact Detail',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgbzdv',
                'stbzdv',
            ],
        ],
        [
            'name' => 'Edit field "Closed Date" on contact detail',
            'system_name' => 'contacts_notowned_closeddate_edit',
            'display_name' => 'User can edit "Closed Date" field on Contact Detail',
            'module_name' => 'contacts',
            'description' => 'User can edit "Closed Date" field on Contact Detail',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgbzdv',
                'stbzdv',
            ],
        ],
        [
            'name' => 'Access to "Tasks" module',
            'system_name' => 'tasks_access',
            'display_name' => 'Access to the Tasks module',
            'module_name' => 'tasks',
            'description' => 'Access to the Tasks module',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View all tasks',
            'system_name' => 'tasks_all_view',
            'display_name' => 'View all tasks',
            'module_name' => 'tasks',
            'description' => 'View all tasks',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'View tasks assigned to you',
            'system_name' => 'tasks_own_view',
            'display_name' => 'View tasks created by the user',
            'module_name' => 'tasks',
            'description' => 'View tasks created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'View tasks assigned to team members',
            'system_name' => 'tasks_team_view',
            'display_name' => 'View tasks of team members',
            'module_name' => 'tasks',
            'description' => 'View tasks of team members',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Manage task templates',
            'system_name' => 'tasks_templates',
            'display_name' => 'Add/Edit/Delete task templates',
            'module_name' => 'tasks',
            'description' => 'Add/Edit/Delete task templates',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'Add tasks from a template',
            'system_name' => 'task_list_Add',
            'display_name' => 'Apply a task template',
            'module_name' => 'tasks',
            'description' => 'Apply a task template',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Assign a task to all users/groups',
            'system_name' => 'task_all_assign',
            'display_name' => 'Assign a task to any user of the task system',
            'module_name' => 'tasks',
            'description' => 'Assign a task to any user of the task system',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ],
        ],
        [
            'name' => 'Assign a task only to team members',
            'system_name' => 'task_team_assign',
            'display_name' => 'Assign a task to a team member',
            'module_name' => 'tasks',
            'description' => 'Assign a task to a team member',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Delete all tasks',
            'system_name' => 'tasks_all_delete',
            'display_name' => 'Delete any task',
            'module_name' => 'tasks',
            'description' => 'Delete any task',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgagsv',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
            ],
        ],
        [
            'name' => 'Delete own tasks',
            'system_name' => 'tasks_own_delete',
            'display_name' => 'Delete only a task the user created',
            'module_name' => 'tasks',
            'description' => 'Delete only a task the user created',
            'roles' => [
                'stcomp',
                'stagsv',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Edit own tasks',
            'system_name' => 'tasks_own_edit',
            'display_name' => 'Edit only tasks created by the user',
            'module_name' => 'tasks',
            'description' => 'Edit only tasks created by the user',
            'roles' => [
                'acctex',
                'agntaf',
            ],
        ],
        [
            'name' => 'Edit all tasks',
            'system_name' => 'tasks_all_edit',
            'display_name' => 'Edit any task',
            'module_name' => 'tasks',
            'description' => 'Edit any task',
            'roles' => [
                'adsupr',
                'adbrok',
                'adsyst',
                'mgcomp',
                'mgclsv',
                'mgbzdv',
                'mgleas',
                'mgmtnc',
                'mgacct',
                'mglsen',
                'stcomp',
                'stclsv',
                'stbzdv',
                'stleas',
                'stmtnc',
                'stacct',
                'stlsen',
            ]
        ],
    ],
];
